  # this is a ci/cd file for index.html apps
  name: CI/CD Web APPS
  on: 
   push:
    branches: [ "main" ]

  jobs:
   BULID_DOCKER_IMAGE: 
    runs-on: ubuntu-latest
    steps:
     - name: Check if docker is installed 
       run: docker --version

     - name: copy local files to remopte runner 
       uses: actions/checkout@v3 
      


     - name: Bulid Docker images form Dockerfile 
       run: docker build -t khalaf .

     - name: Check if docker images is created 
       run: docker images | grep khalaf 

     - name: Login to DockerHub 
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     
     - name: Push Created image to dockerhub 
       run: |
          docker tag khalaf khalaf:2.1
          docker tag khalaf:2.1 khalafahmad/test_repo:2.1
          docker push khalafahmad/test_repo:2.1