  # this is a ci/cd file for index.html apps
  name: CI/CD Web APPS
  on: 
   push:
    branches: [ "main" ]

  jobs:
   build: 
    runs-on: ubuntu-latest
    steps:
     - name: run one-command
       run: echo "Hi hmad Khalaf"

     - name: copy local files to remopte runner 
       uses: actions/checkout@v3 

     - name: check if files is uploaded 
       run: |
          pwd
          ls -a 